package co.edu.uptc.client.view;

import co.edu.uptc.client.net.Request;
import co.edu.uptc.client.net.Response;
import co.edu.uptc.client.net.TransactionData;
import co.edu.uptc.client.presenter.ClientPresenter;
import com.google.gson.Gson;

import java.io.IOException;
import java.util.Scanner;

public class TransactionView {
    private ClientPresenter presenter;
    private Gson gson;

    public TransactionView(ClientPresenter presenter) {
        this.presenter = presenter;
        this.gson = new Gson();
    }

    public void display() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Transaction Menu:\n1. Add Transaction\n2. View Transactions\n3. Edit Transaction\n4. Delete Transaction\n5. Back");
        String option = scanner.nextLine();

        try {
            switch (option) {
                case "1":
                    addTransaction();
                    break;
                case "2":
                    viewTransactions();
                    break;
                case "3":
                    editTransaction();
                    break;
                case "4":
                    deleteTransaction();
                    break;
                case "5":
                    presenter.getLoginView().display();
                    break;
                default:
                    showMessage("Invalid option. Try again.");
                    display();
                    break;
            }
        } catch (IOException e) {
            showMessage("Error: " + e.getMessage());
        }
    }

    private void addTransaction() throws IOException {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter amount: ");
        double amount = Double.parseDouble(scanner.nextLine());

        System.out.print("Enter description: ");
        String description = scanner.nextLine();

        System.out.print("Enter type (income/expense): ");
        String type = scanner.nextLine();

        // Get the current date and time
        String dateTime = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        // Display predefined categories
        System.out.println("Select a category:");
        System.out.println("1. Alimentación");
        System.out.println("2. Transporte");
        System.out.println("3. Vivienda");
        System.out.println("4. Salud");
        System.out.println("5. Entretenimiento");
        System.out.println("6. Ropa y Calzado");
        System.out.println("7. Otros Gastos");
        String category = "";
        switch (scanner.nextLine()) {
            case "1":
                category = "Alimentación";
                break;
            case "2":
                category = "Transporte";
                break;
            case "3":
                category = "Vivienda";
                break;
            case "4":
                category = "Salud";
                break;
            case "5":
                category = "Entretenimiento";
                break;
            case "6":
                category = "Ropa y Calzado";
                break;
            case "7":
                category = "Otros Gastos";
                break;
            default:
                showMessage("Invalid category. Try again.");
                display();
                return;
        }

        // Create a TransactionData object and set the values
        TransactionData transactionData = new TransactionData(
                presenter.getLoginView().getCurrentUser().getUsername(), // Ensure this fetches the correct identifier
                null, // Transaction ID will be generated by the server
                amount,
                dateTime,
                category,
                description,
                type
        );

        String transactionDataJson = gson.toJson(transactionData);
        Request request = new Request("addTransaction", transactionDataJson);
        presenter.getConnection().sendRequest(request);
        Response response = presenter.getConnection().receiveResponse();
        showMessage(response.getData());
        display();
    }

    private void viewTransactions() throws IOException {
        String userId = presenter.getLoginView().getCurrentUser().getUsername(); // Ensure this fetches the correct identifier
        Request request = new Request("viewTransactions", userId);
        presenter.getConnection().sendRequest(request);
        Response response = presenter.getConnection().receiveResponse();

        if ("success".equals(response.getStatus())) {
            TransactionData[] transactions = gson.fromJson(response.getData(), TransactionData[].class);
            for (TransactionData transaction : transactions) {
                System.out.println(transaction);
            }
        } else {
            showMessage("Error: " + response.getData());
        }
        display();
    }

    private void editTransaction() throws IOException {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter Transaction ID to edit: ");
        String transactionId = scanner.nextLine();

        System.out.print("Enter new amount: ");
        double amount = Double.parseDouble(scanner.nextLine());

        System.out.print("Enter new description: ");
        String description = scanner.nextLine();

        System.out.print("Enter new type (income/expense): ");
        String type = scanner.nextLine();

        // Get the current date and time
        String dateTime = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        // Display predefined categories
        System.out.println("Select a new category:");
        System.out.println("1. Alimentación");
        System.out.println("2. Transporte");
        System.out.println("3. Vivienda");
        System.out.println("4. Salud");
        System.out.println("5. Entretenimiento");
        System.out.println("6. Ropa y Calzado");
        System.out.println("7. Otros Gastos");
        String category = "";
        switch (scanner.nextLine()) {
            case "1":
                category = "Alimentación";
                break;
            case "2":
                category = "Transporte";
                break;
            case "3":
                category = "Vivienda";
                break;
            case "4":
                category = "Salud";
                break;
            case "5":
                category = "Entretenimiento";
                break;
            case "6":
                category = "Ropa y Calzado";
                break;
            case "7":
                category = "Otros Gastos";
                break;
            default:
                showMessage("Invalid category. Try again.");
                display();
                return;
        }

        // Create a TransactionData object and set the values
        TransactionData transactionData = new TransactionData(
                presenter.getLoginView().getCurrentUser().getUsername(),
                transactionId,
                amount,
                dateTime,
                category,
                description,
                type
        );

        String transactionDataJson = gson.toJson(transactionData);
        Request request = new Request("editTransaction", transactionDataJson);
        presenter.getConnection().sendRequest(request);
        Response response = presenter.getConnection().receiveResponse();
        showMessage(response.getData());
        display();
    }

    private void deleteTransaction() throws IOException {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter Transaction ID to delete: ");
        String transactionId = scanner.nextLine();

        Request request = new Request("deleteTransaction", transactionId);
        presenter.getConnection().sendRequest(request);
        Response response = presenter.getConnection().receiveResponse();
        showMessage(response.getData());
        display();
    }

    public void showMessage(String message) {
        System.out.println(message);
    }
}
